#!/usr/bin/env python3
"""
QuantPricer — Publication-Quality Visualization Suite

Reads CSV data generated by tools/generate_data.cpp and produces
industry-standard plots for all pricing models.

Usage:
    make viz          # build data generator, run it, then plot
    python3 tools/visualize.py   # just plot (if CSVs already exist)
"""

import os
import sys
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import cm
from mpl_toolkits.mplot3d import Axes3D  # noqa: F401

# Style — dark theme, publication quality
plt.style.use("dark_background")
plt.rcParams.update({
    "figure.figsize": (12, 7),
    "figure.dpi": 150,
    "font.size": 11,
    "axes.titlesize": 14,
    "axes.labelsize": 12,
    "legend.fontsize": 10,
    "lines.linewidth": 2,
    "axes.grid": True,
    "grid.alpha": 0.3,
    "savefig.bbox": "tight",
    "savefig.pad_inches": 0.2,
})

OUTPUT_DIR = "plots"
os.makedirs(OUTPUT_DIR, exist_ok=True)

ACCENT   = "#00d4ff"
ACCENT2  = "#ff6b6b"
ACCENT3  = "#51cf66"
ACCENT4  = "#ffd43b"
ACCENT5  = "#cc5de8"
COLORS   = [ACCENT, ACCENT2, ACCENT3, ACCENT4, ACCENT5, "#ff922b", "#20c997"]


def save(fig, name):
    path = os.path.join(OUTPUT_DIR, f"{name}.png")
    fig.savefig(path)
    plt.close(fig)
    print(f"    saved {path}")


# ============================================================================
# 1. Volatility Surface
# ============================================================================
def plot_vol_surface():
    df = pd.read_csv("viz_vol_surface.csv")
    strikes = sorted(df["Strike"].unique())
    mats = sorted(df["Maturity"].unique())

    K, T = np.meshgrid(strikes, mats)
    IV = np.full_like(K, np.nan, dtype=float)

    for i, t in enumerate(mats):
        for j, k in enumerate(strikes):
            row = df[(df["Maturity"] == t) & (df["Strike"] == k)]
            if not row.empty:
                IV[i, j] = row["ImpliedVol"].values[0]

    fig = plt.figure(figsize=(14, 9))
    ax = fig.add_subplot(111, projection="3d")
    surf = ax.plot_surface(K, T, IV * 100, cmap=cm.plasma, alpha=0.9,
                           edgecolor="white", linewidth=0.2)
    ax.set_xlabel("Strike", labelpad=10)
    ax.set_ylabel("Maturity (years)", labelpad=10)
    ax.set_zlabel("Implied Vol (%)", labelpad=10)
    ax.set_title("Heston Implied Volatility Surface\n"
                 r"$v_0=0.04,\ \kappa=2,\ \theta=0.04,\ \xi=0.3,\ \rho=-0.7$",
                 fontsize=14, pad=20)
    fig.colorbar(surf, ax=ax, shrink=0.5, label="IV (%)")
    ax.view_init(elev=25, azim=-45)
    save(fig, "01_vol_surface")

    # 2D smile slices
    fig, ax = plt.subplots(figsize=(12, 7))
    for i, t in enumerate(mats):
        subset = df[df["Maturity"] == t].sort_values("Strike")
        if len(subset) > 3:
            ax.plot(subset["Strike"], subset["ImpliedVol"] * 100,
                    "o-", color=COLORS[i % len(COLORS)], label=f"T={t:.2f}y",
                    markersize=5)
    ax.axvline(100, color="white", alpha=0.3, linestyle="--", label="ATM")
    ax.set_xlabel("Strike")
    ax.set_ylabel("Implied Volatility (%)")
    ax.set_title("Heston Volatility Smile — Skew by Maturity")
    ax.legend()
    save(fig, "02_vol_smile")


# ============================================================================
# 2. Greeks Dashboard
# ============================================================================
def plot_greeks():
    df = pd.read_csv("viz_greeks.csv")

    fig, axes = plt.subplots(2, 3, figsize=(18, 11))
    fig.suptitle("Black-Scholes Greeks Dashboard  |  K=100, r=5%, T=1y, σ=20%",
                 fontsize=16, y=0.98)

    # Price
    ax = axes[0, 0]
    ax.plot(df["Spot"], df["CallPrice"], color=ACCENT, label="Call")
    ax.plot(df["Spot"], df["PutPrice"], color=ACCENT2, label="Put")
    ax.fill_between(df["Spot"], 0, df["CallPrice"], alpha=0.1, color=ACCENT)
    ax.fill_between(df["Spot"], 0, df["PutPrice"], alpha=0.1, color=ACCENT2)
    ax.set_title("Option Price")
    ax.set_xlabel("Spot"); ax.set_ylabel("Price ($)")
    ax.legend()

    # Delta
    ax = axes[0, 1]
    ax.plot(df["Spot"], df["DeltaCall"], color=ACCENT, label="Call Δ")
    ax.plot(df["Spot"], df["DeltaPut"], color=ACCENT2, label="Put Δ")
    ax.axhline(0, color="white", alpha=0.3, linewidth=0.8)
    ax.set_title("Delta (Δ)")
    ax.set_xlabel("Spot"); ax.set_ylabel("Delta")
    ax.legend()

    # Gamma
    ax = axes[0, 2]
    ax.plot(df["Spot"], df["Gamma"], color=ACCENT3)
    ax.fill_between(df["Spot"], 0, df["Gamma"], alpha=0.15, color=ACCENT3)
    ax.set_title("Gamma (Γ)")
    ax.set_xlabel("Spot"); ax.set_ylabel("Gamma")

    # Vega
    ax = axes[1, 0]
    ax.plot(df["Spot"], df["Vega"], color=ACCENT4)
    ax.fill_between(df["Spot"], 0, df["Vega"], alpha=0.15, color=ACCENT4)
    ax.set_title("Vega (ν)")
    ax.set_xlabel("Spot"); ax.set_ylabel("Vega")

    # Theta
    ax = axes[1, 1]
    ax.plot(df["Spot"], df["ThetaCall"], color=ACCENT, label="Call Θ")
    ax.plot(df["Spot"], df["ThetaPut"], color=ACCENT2, label="Put Θ")
    ax.axhline(0, color="white", alpha=0.3, linewidth=0.8)
    ax.set_title("Theta (Θ)")
    ax.set_xlabel("Spot"); ax.set_ylabel("Theta ($/day)")
    ax.legend()

    # Rho
    ax = axes[1, 2]
    ax.plot(df["Spot"], df["RhoCall"], color=ACCENT5)
    ax.set_title("Rho (ρ)")
    ax.set_xlabel("Spot"); ax.set_ylabel("Rho")

    plt.tight_layout()
    save(fig, "03_greeks_dashboard")


# ============================================================================
# 3. Monte Carlo Convergence
# ============================================================================
def plot_mc_convergence():
    df = pd.read_csv("viz_mc_convergence.csv")

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 7))

    # Price convergence
    ax1.fill_between(df["NumPaths"], df["ConfLo"], df["ConfHi"],
                     alpha=0.2, color=ACCENT, label="95% CI")
    ax1.plot(df["NumPaths"], df["MCPrice"], "o-", color=ACCENT,
             markersize=3, label="MC Price")
    ax1.axhline(df["AnalyticPrice"].iloc[0], color=ACCENT2,
                linestyle="--", label="Analytic (BS)")
    ax1.set_xscale("log")
    ax1.set_xlabel("Number of Paths")
    ax1.set_ylabel("Price ($)")
    ax1.set_title("MC Price Convergence")
    ax1.legend()

    # Standard error convergence
    ax2.plot(df["NumPaths"], df["StdError"], "o-", color=ACCENT3, markersize=3)
    # Theoretical 1/sqrt(N) line
    N = df["NumPaths"].values.astype(float)
    se0 = df["StdError"].iloc[0] * np.sqrt(N[0])
    ax2.plot(N, se0 / np.sqrt(N), "--", color=ACCENT2,
             label=r"$O(1/\sqrt{N})$ theory", alpha=0.7)
    ax2.set_xscale("log")
    ax2.set_yscale("log")
    ax2.set_xlabel("Number of Paths")
    ax2.set_ylabel("Standard Error")
    ax2.set_title("MC Standard Error (log-log)")
    ax2.legend()

    fig.suptitle("Monte Carlo Convergence — European Call (Antithetic Variates)",
                 fontsize=14, y=1.02)
    plt.tight_layout()
    save(fig, "04_mc_convergence")


# ============================================================================
# 4. Barrier Analysis
# ============================================================================
def plot_barrier():
    df = pd.read_csv("viz_barrier.csv")

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 7))

    ax1.plot(df["Barrier"], df["DOCallPrice"], color=ACCENT, label="Down-and-Out Call")
    ax1.plot(df["Barrier"], df["DICallPrice"], color=ACCENT2, label="Down-and-In Call")
    ax1.axhline(df["VanillaCall"].iloc[0], color="white", alpha=0.4,
                linestyle="--", label="Vanilla Call")
    ax1.fill_between(df["Barrier"], df["DOCallPrice"], df["VanillaCall"].iloc[0],
                     alpha=0.1, color=ACCENT)
    ax1.set_xlabel("Barrier Level (H)")
    ax1.set_ylabel("Price ($)")
    ax1.set_title("Barrier Option Price vs Barrier Level")
    ax1.legend()

    ax2.plot(df["Barrier"], df["KnockPct"], color=ACCENT4, linewidth=2.5)
    ax2.fill_between(df["Barrier"], 0, df["KnockPct"], alpha=0.15, color=ACCENT4)
    ax2.set_xlabel("Barrier Level (H)")
    ax2.set_ylabel("Knock-Out Probability (%)")
    ax2.set_title("Probability of Hitting Barrier (252-step MC)")

    fig.suptitle("Down Barrier Analysis — S₀=100, K=100, σ=20%, T=1y",
                 fontsize=14, y=1.02)
    plt.tight_layout()
    save(fig, "05_barrier_analysis")


# ============================================================================
# 5. Correlation Impact
# ============================================================================
def plot_correlation():
    df = pd.read_csv("viz_correlation.csv")

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 7))

    ax1.plot(df["Rho"], df["BestOfCall"], "o-", color=ACCENT, label="Best-of Call")
    ax1.plot(df["Rho"], df["WorstOfCall"], "s-", color=ACCENT2, label="Worst-of Call")
    ax1.plot(df["Rho"], df["BasketCall"], "^-", color=ACCENT3, label="Basket Call")
    ax1.plot(df["Rho"], df["ExchangeOption"], "D-", color=ACCENT4, label="Exchange Option")
    ax1.set_xlabel("Correlation (ρ)")
    ax1.set_ylabel("Price ($)")
    ax1.set_title("Multi-Asset Option Prices vs Correlation")
    ax1.legend()

    ax2.plot(df["Rho"], df["BasketVol"] * 100, "o-", color=ACCENT5, linewidth=2.5)
    ax2.fill_between(df["Rho"], 0, df["BasketVol"] * 100, alpha=0.15, color=ACCENT5)
    ax2.axhline(20, color="white", alpha=0.3, linestyle="--", label="σ_individual = 20%")
    ax2.set_xlabel("Correlation (ρ)")
    ax2.set_ylabel("Basket Volatility (%)")
    ax2.set_title("Basket Vol vs Correlation (Diversification Effect)")
    ax2.legend()

    fig.suptitle("The Correlation Trade — 2 Assets, S₀=100, σ=20%",
                 fontsize=14, y=1.02)
    plt.tight_layout()
    save(fig, "06_correlation_impact")


# ============================================================================
# 6. FDM Solution
# ============================================================================
def plot_fdm():
    df = pd.read_csv("viz_fdm_grid.csv")

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 7))

    ax1.plot(df["Spot"], df["AnalyticCall"], "--", color="white", alpha=0.6,
             label="BS Analytic", linewidth=1.5)
    ax1.plot(df["Spot"], df["FDMCall"], color=ACCENT, label="FDM (Crank-Nicolson)")
    ax1.plot(df["Spot"], df["Intrinsic"], ":", color=ACCENT2, alpha=0.5,
             label="Intrinsic max(S-K,0)")
    ax1.set_xlabel("Spot Price")
    ax1.set_ylabel("Call Value ($)")
    ax1.set_title("European Call — FDM vs Analytic")
    ax1.set_xlim(50, 200)
    ax1.legend()

    ax2.plot(df["Spot"], df["AnalyticPut"], "--", color="white", alpha=0.6,
             label="BS Analytic", linewidth=1.5)
    ax2.plot(df["Spot"], df["FDMPut"], color=ACCENT2, label="FDM (Crank-Nicolson)")
    ax2.set_xlabel("Spot Price")
    ax2.set_ylabel("Put Value ($)")
    ax2.set_title("European Put — FDM vs Analytic")
    ax2.set_xlim(50, 200)
    ax2.legend()

    fig.suptitle("Finite Difference Method — Crank-Nicolson Solution (400×2000 grid)",
                 fontsize=14, y=1.02)
    plt.tight_layout()
    save(fig, "07_fdm_solution")


# ============================================================================
# 7. American vs European
# ============================================================================
def plot_american():
    df = pd.read_csv("viz_american.csv")

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 7))

    ax1.plot(df["Spot"], df["AmePut"], color=ACCENT, label="American Put", linewidth=2.5)
    ax1.plot(df["Spot"], df["EurPut"], "--", color=ACCENT2, label="European Put")
    intrinsic = np.maximum(100 - df["Spot"], 0)
    ax1.plot(df["Spot"], intrinsic, ":", color="white", alpha=0.4, label="Intrinsic")
    ax1.fill_between(df["Spot"], df["EurPut"], df["AmePut"], alpha=0.15, color=ACCENT3)
    ax1.set_xlabel("Spot Price")
    ax1.set_ylabel("Put Value ($)")
    ax1.set_title("American vs European Put")
    ax1.legend()

    ax2.plot(df["Spot"], df["EEPremium"], color=ACCENT3, linewidth=2.5)
    ax2.fill_between(df["Spot"], 0, df["EEPremium"], alpha=0.2, color=ACCENT3)
    ax2.set_xlabel("Spot Price")
    ax2.set_ylabel("Early Exercise Premium ($)")
    ax2.set_title("Early Exercise Premium (American − European)")

    fig.suptitle("American Option Analysis — K=100, r=5%, T=1y, σ=20% (Binomial Tree N=1000)",
                 fontsize=13, y=1.02)
    plt.tight_layout()
    save(fig, "08_american_vs_european")


# ============================================================================
# 8. Model Comparison
# ============================================================================
def plot_model_comparison():
    df = pd.read_csv("viz_model_comparison.csv")

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 7))

    ax1.plot(df["Strike"], df["BSPrice"], "--", color="white", alpha=0.5, label="Black-Scholes")
    ax1.plot(df["Strike"], df["HestonPrice"], "o-", color=ACCENT, markersize=4,
             label="Heston (ρ=−0.7)")
    ax1.plot(df["Strike"], df["MertonPrice"], "s-", color=ACCENT2, markersize=4,
             label="Merton Jump-Diffusion")
    ax1.set_xlabel("Strike")
    ax1.set_ylabel("Call Price ($)")
    ax1.set_title("Call Prices Across Models")
    ax1.legend()

    hiv = df["HestonIV"].replace(0, np.nan) * 100
    miv = df["MertonIV"].replace(0, np.nan) * 100
    ax2.axhline(20, color="white", alpha=0.3, linestyle="--", label="BS flat vol = 20%")
    ax2.plot(df["Strike"], hiv, "o-", color=ACCENT, markersize=4,
             label="Heston IV")
    ax2.plot(df["Strike"], miv, "s-", color=ACCENT2, markersize=4,
             label="Merton IV")
    ax2.set_xlabel("Strike")
    ax2.set_ylabel("Implied Volatility (%)")
    ax2.set_title("Implied Volatility Smile by Model")
    ax2.legend()

    fig.suptitle("Model Comparison — S=100, T=1y | BS vs Heston vs Merton",
                 fontsize=14, y=1.02)
    plt.tight_layout()
    save(fig, "09_model_comparison")


# ============================================================================
# 9. Payoff Profiles
# ============================================================================
def plot_payoffs():
    df = pd.read_csv("viz_payoffs.csv")

    fig, axes = plt.subplots(1, 3, figsize=(18, 6))

    # Call
    ax = axes[0]
    ax.plot(df["Spot"], df["CallPayoff"], ":", color="white", alpha=0.4, label="Payoff at T")
    ax.plot(df["Spot"], df["CallValue"], color=ACCENT, label="Value today")
    ax.fill_between(df["Spot"], 0, df["CallValue"], alpha=0.1, color=ACCENT)
    ax.axvline(100, color="white", alpha=0.2, linestyle="--")
    ax.set_title("European Call")
    ax.set_xlabel("Spot"); ax.set_ylabel("Value ($)")
    ax.legend()

    # Put
    ax = axes[1]
    ax.plot(df["Spot"], df["PutPayoff"], ":", color="white", alpha=0.4, label="Payoff at T")
    ax.plot(df["Spot"], df["PutValue"], color=ACCENT2, label="Value today")
    ax.fill_between(df["Spot"], 0, df["PutValue"], alpha=0.1, color=ACCENT2)
    ax.axvline(100, color="white", alpha=0.2, linestyle="--")
    ax.set_title("European Put")
    ax.set_xlabel("Spot"); ax.set_ylabel("Value ($)")
    ax.legend()

    # Straddle
    ax = axes[2]
    ax.plot(df["Spot"], df["Straddle"], ":", color="white", alpha=0.4, label="Payoff at T")
    ax.plot(df["Spot"], df["StraddleValue"], color=ACCENT3, label="Value today")
    ax.fill_between(df["Spot"], 0, df["StraddleValue"], alpha=0.1, color=ACCENT3)
    ax.axvline(100, color="white", alpha=0.2, linestyle="--")
    ax.set_title("Straddle (Call + Put)")
    ax.set_xlabel("Spot"); ax.set_ylabel("Value ($)")
    ax.legend()

    fig.suptitle("Option Payoff Profiles — K=100, r=5%, T=1y, σ=20%",
                 fontsize=14, y=1.02)
    plt.tight_layout()
    save(fig, "10_payoff_profiles")


# ============================================================================
# 10. Basket Vol
# ============================================================================
def plot_basket_vol():
    df = pd.read_csv("viz_basket_vol.csv")

    fig, ax = plt.subplots(figsize=(12, 7))
    labels = ["ρ=0.0", "ρ=0.3", "ρ=0.5", "ρ=0.8", "ρ=1.0"]
    cols = [c for c in df.columns if c != "N"]

    for i, (col, label) in enumerate(zip(cols, labels)):
        ax.plot(df["N"], df[col] * 100, "o-", color=COLORS[i], label=label, markersize=5)

    # Asymptotic limits
    sigma = 20
    for rho, color in zip([0.0, 0.3, 0.5, 0.8, 1.0], COLORS):
        limit = sigma * np.sqrt(max(rho, 0))
        ax.axhline(limit, color=color, alpha=0.3, linestyle=":")

    ax.set_xlabel("Number of Assets (N)")
    ax.set_ylabel("Basket Volatility (%)")
    ax.set_title("Diversification Effect — Basket Vol vs Number of Assets\n"
                 r"Limit as $N \to \infty$: $\sigma_{basket} \to \sigma\sqrt{\rho}$")
    ax.legend()
    ax.set_ylim(bottom=0)
    save(fig, "11_basket_vol")


# ============================================================================
# Main
# ============================================================================
def main():
    print("=" * 60)
    print("  QuantPricer — Generating Visualizations")
    print("=" * 60)
    print()

    plots = [
        ("Volatility Surface",    "viz_vol_surface.csv",     plot_vol_surface),
        ("Greeks Dashboard",      "viz_greeks.csv",          plot_greeks),
        ("MC Convergence",        "viz_mc_convergence.csv",  plot_mc_convergence),
        ("Barrier Analysis",      "viz_barrier.csv",         plot_barrier),
        ("Correlation Impact",    "viz_correlation.csv",     plot_correlation),
        ("FDM Solution",          "viz_fdm_grid.csv",        plot_fdm),
        ("American vs European",  "viz_american.csv",        plot_american),
        ("Model Comparison",      "viz_model_comparison.csv",plot_model_comparison),
        ("Payoff Profiles",       "viz_payoffs.csv",         plot_payoffs),
        ("Basket Volatility",     "viz_basket_vol.csv",      plot_basket_vol),
    ]

    for name, csv_file, plot_fn in plots:
        if os.path.exists(csv_file):
            print(f"  [{plots.index((name, csv_file, plot_fn))+1:2d}/10] {name}...")
            plot_fn()
        else:
            print(f"  [{plots.index((name, csv_file, plot_fn))+1:2d}/10] {name} — SKIPPED (no {csv_file})")

    print(f"\n  All plots saved to {OUTPUT_DIR}/")
    print("=" * 60)


if __name__ == "__main__":
    main()
